# Generated by Django 3.1.2 on 2020-10-21 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id unico de cada producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=25)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=4)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
    ]
