# Generated by Django 3.1.2 on 2020-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alto del produscto(Solo si espesifica)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del producto(solo si se especifica)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, help_text='Color del producto, solo si se puede', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(help_text='Modelo del producto', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del producto (solo si se espesifica)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(help_text='Precio del producto'),
        ),
    ]
