# Generated by Django 3.1.2 on 2020-10-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20201021_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ManyToManyField(help_text='Seleccione una marca para este producto', to='catalogo.Marca'),
        ),
    ]
