# Generated by Django 3.1.2 on 2020-11-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alto del produscto(puede quedar en blanco)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del producto(puede quedar en blanco)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, help_text='Color del producto(Puede quedar en blanco)', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del producto (puede quedar en blanco)', max_digits=4, null=True),
        ),
    ]
