# Generated by Django 3.1.2 on 2020-11-02 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20201102_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Id unico de cada producto', primary_key=True, serialize=False),
        ),
    ]
