# Generated by Django 3.1.2 on 2020-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20201112_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo', verbose_name='Imagen'),
        ),
    ]
