# Generated by Django 3.1.2 on 2020-11-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_auto_20201113_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(help_text='Nombre completo', max_length=100)),
                ('run', models.CharField(help_text='Ingrese run', max_length=100)),
                ('cantidad', models.PositiveIntegerField(help_text='Ingrese cantidad')),
                ('telefono', models.PositiveIntegerField(help_text='Ingrese teléfono de contacto')),
                ('coreo', models.CharField(blank=True, help_text='Correo', max_length=25, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen')),
                ('tipo', models.CharField(blank=True, choices=[('d', 'Default'), ('c', 'Custom')], default='d', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
    ]
